### ISSUE TITLE
『小助手』COZE - 免费GPT4 样式失效，开启后显示空内容

### ISSUE THREAD

**Issue by tasselx** [Hunlongyu/userscript#2]
应该是coze的样式修改了，导致现在脚本失效了
![image](https://github.com/Hunlongyu/userscript/assets/2656142/0df0469e-ac1c-4734-9ab3-f872579ea9d0)

**Comment by stackoverflow1024** [comment]
I'm experiencing a layout issue with Coze when enabling the plugin. It seems the layout has become distorted recently.  Would it be possible to add a patch to address this problem?


<img width="1276" alt="IMG_2024-04-28_18-00-32" src="https://github.com/Hunlongyu/userscript/assets/2871048/7aabe5ad-9d14-47a8-8342-0f4a6bf50d22">

**Comment by Hunlongyu** [comment]
已经更新了，升级到 0.8.8 即可。

**Comment by Hunlongyu** [comment]
> I'm experiencing a layout issue with Coze when enabling the plugin. It seems the layout has become distorted recently. Would it be possible to add a patch to address this problem?
> 
> <img alt="IMG_2024-04-28_18-00-32" width="1276" src="https://private-user-images.githubusercontent.com/2871048/326301822-7aabe5ad-9d14-47a8-8342-0f4a6bf50d22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjk4MjAsIm5iZiI6MTcxNDM2OTUyMCwicGF0aCI6Ii8yODcxMDQ4LzMyNjMwMTgyMi03YWFiZTVhZC05ZDE0LTQ3YTgtODM0Mi0wZjRhNmJmNTBkMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMDU0NTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU0MWE3N2VkM2I3NzYxMDEzYjllZmZlOTEzMzA3YTkyZDgyMjgzNzVkMTI5YmIxMzZmOWUwMmEzMzFlNDkwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gBkvQh4FFgVZiJQ-JAJRv4TQ1CkKk1ORsAJ69uTuUD0">

have already been solved
